### ISSUE TITLE
DC MOTOR BATEN KONTROLAREN ULERMEN ARIKETAK

### ISSUE THREAD

**Issue by ArmandoLLSB** [LSB-GE1/Erronka-10-Lerro-jarraitzailea---1-Taldea#11]
- [x] 1.-Elikatu  DC motor bat tentsio jarraiko elikadura iturri batekin eta potentziometro batez, DC motorra-ari aplikatu diezaiokegun tentsioa kontrolatzeko moduan.

- [x] Zer gertatzen da motorra tentsio desberdinetan elikatuz.
- [x] Zergatik aldatzen da abiadura?
- [x] Nola aldatu ahalko genioke biraketaren noranzkoa?
- [x] Zein dira motorren ezaugarri nagusiak?
- [x] Zein da motorraren Potentzia, Abiadura eta Par-aren arteko erlazioa?
- [x] Zein da motor baten eta sorgailu baten arteko ezberdintasuna?
- [x] Noiz funtzionatzen du motor batek sorgailu moduan?
- [x] Nola funtzionatzen du DC motor batek?

- [x] 2.- DC motor baten kontrola:

- [x] Aztertu LM293D osagaia
- [x] Ze sarrera ditu?
- [x] Ze irteera?
- [x] Nola elikatzen da?
- [x] Zein da bere barne osaera?
- [x] Simulatu eskemako zirkuitua Proteus-en (Dagokion sketch-a erabiliaz). Potentziometroaren doikuntza aldatuz ikusi ondorioak.
- [x] Muntatu eskemako zirkuitua Protoboard batean (Dagokion sketch-a erabiliaz) Potentziometroaren doikuntza aldatuz ikusi ondorioak.
- [x] Ozsilozkopio batez neurtu ondorengo seinaleen anplitudea eta frekuentzia, potentziometroaren doikuntza aldatuz.
- [x] LM239D-aren IN1 eta IN2 sarrerak. Konparatu biak.
- [x] LM239D-aren OUT1 eta OUT2 irteerak. Konparatu biak.
- [x] Motorraren elikadura tentsioa.
- [x] Enkoderraren seinalea
- [x] Galderak:
- [x] Zertan eragiten dugu motorraren funtzionamendu egoera aldatzeko.
- [x] Nola lortzen dugu motorrari aplikatzen zaion tentsioa aldatzea? Nola deitzen zaio teknika honi?
- [x] Zergaitik erabiltzen da LM293D driver-a?
- [x] Erabili dugun kontrol mota nolakoa da enkoder-a ez dugula erabiltzen kontuan hartuta? Zer hobekuntza eman ahal digu enkoder-a erabiltzeak?
- [ ]

**Comment by AnderELSB** [comment]
ariketa bukatuta dago
